# Generated by Django 5.2.4 on 2025-08-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="room",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="room",
            name="name",
            field=models.CharField(default="Untitled Room", max_length=200),
        ),
    ]
